### ISSUE TITLE
spring-boot-starter-dubbo 报错 配置都正确

### ISSUE THREAD

**Issue by newajax-1** [alibaba/spring-boot-starter-dubbo#7]
Caused by: java.lang.IllegalArgumentException: interface com.qf.posp.depo.notify.api.api.INotifyRecordService is not visible from class loader
	at com.alibaba.dubbo.common.bytecode.Proxy.getProxy(Proxy.java:98) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.common.bytecode.Proxy.getProxy(Proxy.java:67) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory.getProxy(JavassistProxyFactory.java:35) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyFactory.getProxy(AbstractProxyFactory.java:49) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.proxy.wrapper.StubProxyFactoryWrapper.getProxy(StubProxyFactoryWrapper.java:60) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.ProxyFactory$Adpative.getProxy(ProxyFactory$Adpative.java) ~[na:2.5.3]
	at com.alibaba.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:426) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:300) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:138) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.config.spring.ReferenceBean.getObject(ReferenceBean.java:65) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.boot.dubbo.DubboConsumerAutoConfiguration$1.postProcessBeforeInitialization(DubboConsumerAutoConfiguration.java:96) ~[spring-boot-starter-dubbo-1.0.0-SNAPSHOT.jar:na]
	... 23 common frames omitted

**Comment by xionghuiCoder** [comment]
提示 class loader 加载class失败；参考下: http://stackoverflow.com/questions/12199732/interface-is-not-visible-from-class-loader

**Comment by newajax-1** [comment]
[https://github.com/dangdangdotcom/dubbox/issues/218](url)
